# Generated by Django 5.0.6 on 2024-06-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(help_text='Bu yerga sarlavha kiritishingiz mumkin', max_length=128, verbose_name='Sarlavha')),
            ],
        ),
    ]
