# Generated by Django 5.0.6 on 2024-07-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_is_delete_task_is_done_alter_task_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tittle',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=1, max_length=128, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
